config/routes.rb
Rails.application.routes.draw do

  scope 'auth' do
    devise_for :parents
    devise_for :teachers
    devise_for :students
    devise_for :users
  end

  resources :users
  resources :parents
  resources :teachers
  resources :exam_categories
  resources :grades

  resources :students
  resources :exams
  resources :courses
  resources :attendances
  resources :classrooms

  root 'dashboard#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :student
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :grade
  belongs_to :teacher
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :grade
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :exam_category
end

app/models/exam_category.rb
class ExamCategory < ApplicationRecord
  has_many :exams
end

app/models/grade.rb
class Grade < ApplicationRecord
  has_many :courses
end

app/models/parent.rb
class Parent < ApplicationRecord

  has_many :students

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, ImageUploader

  GENDER = ['Male', 'Female']

end

app/models/student.rb
class Student < ApplicationRecord

  belongs_to :parent
  has_many :attendances

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, StudentUploader

  GENDER = ['Male', 'Female']
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, TeacherUploader

  GENDER = ['Male', 'Female']
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :email, :password, :gender, :dob, :phone, :address, :lat, :long, :image, :image_cache, :parent_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/students/_form.html.haml
= simple_form_for(@student) do |f|
  = f.error_notification
  .row
    .col-xs-12.col-md-6
      .image-uploader{align: 'center'}
        %a{:href => "#!"}
          = image_tag f.object.image, size: '150x150'
        = f.input :image, as: :file, label: 'Upload Image',
          :label_html => { class: 'btn btn-default'}
        = f.hidden_field :image_cache

      = f.input :name

      .form-group.string.optional.student_parent_id
        %label.control-label.string.optional{for: 'student_parent_id'} Parent
        = f.select :parent_id, Parent.all.map { |p| [p.name + " ("+p.phone+")", p.id]}, {},{class: 'form-control string optional', id: 'student_parent_id'}
      
      = f.input :email
      = f.input :password
      = f.input :dob
      = f.input :phone
      = f.input :gender, collection: Student::GENDER
      = f.input :address

    .col-xs-12.col-md-6
      = f.input :lat, as: :hidden, input_html: {id: 'student-lat'}
      = f.input :long, as: :hidden, input_html: {id: 'student-long'}

      #map-student

  = f.button :submit, class: 'btn btn-primary btn-fill'

app/views/students/edit.html.haml
.col-xs-12.col.md-12
  .card

    .header
      %h4.title Edit Student
      %hr

    .content
      = render 'form'

    %hr
    .footer

      = link_to students_path, class: 'btn btn-default' do
        %i.fa.fa-chevron-left  
        Back
      = link_to @student, class: 'btn btn-info btn-fill' do
        %i.fa.fa-eye
        Show
    %br

app/views/students/index.html.haml
.col-xs-12.col.md-12
  .card

    .header
      %h4.title
        %i.pe-7s-users
        Listing Students
      %hr
      = link_to new_student_path, class: 'btn btn-primary btn-fill' do
        %i.fa.fa-plus-square
        New Student
      %br
      %br

    .content.table-responsive.table-full-width
      %table.table.table-hover.table-striped
        %thead
          %tr
            %th Name
            %th Gender
            %th Phone
            %th Address
            %th Actions

        %tbody
          - @students.each do |student|
            %tr
              %td= student.name
              %td= student.gender
              %td= student.phone
              %td= student.address
              %td
                = link_to student, class: 'btn btn-info btn-sm' do
                  %i.fa.fa-eye
                  Show
                = link_to edit_student_path(student), class: 'btn btn-primary btn-sm' do
                  %i.fa.fa-edit
                  Edit
                = link_to student, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do
                  %i.fa.fa-trash
                  Delete
    %br

app/views/students/new.html.haml
.col-xs-12.col.md-12
  .card

    .header
      %h4.title New Student
      %hr

    .content
      = render 'form'

    %hr
    .footer
      = link_to students_path, class: 'btn btn-default' do
        %i.fa.fa-chevron-left
        Back
    %br

app/views/students/show.html.haml
- if notice.present?
  .alert.alert-info{role: "alert"}= notice
.col-xs-12.col.md-12
  .card

    .header
      %h4.title Student
      %hr

    .content
      .row
        .col-md-6.col-xs-12
          %table.table
            %tr
              %th Image
              %td= image_tag @student.image, size: '150x150'
            %tr
              %th Name
              %td= @student.name
            %tr
              %th Parent Name
              %td= link_to "#{@student.parent.name}", @student.parent
            %tr
              %th Gender
              %td= @student.gender
            %tr
              %th Date of Birth
              %td= @student.dob
            %tr
              %th Phone
              %td= @student.phone
            %tr
              %th Email
              %td= @student.email
            %tr
              %th Address
              %td= @student.address
        .col-md-6.col-xs-12
          %input#lat-value{value: @student.lat, type: 'hidden'}
          %input#long-value{value: @student.long, type: 'hidden'}
          #show-student-map

    .footer
      = link_to students_path, class: 'btn btn-default' do
        %i.fa.fa-chevron-left
        Back
      = link_to edit_student_path(@student), class: 'btn btn-primary btn-fill' do
        %i.fa.fa-edit
        Edit
    %br