config/routes.rb
Rails.application.routes.draw do

  scope 'auth' do
    devise_for :parents
    devise_for :teachers
    devise_for :students
    devise_for :users
  end

  resources :users
  resources :parents
  resources :teachers
  resources :exam_categories
  resources :grades

  resources :students
  resources :exams
  resources :courses
  resources :attendances
  resources :classrooms

  root 'dashboard#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :student
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :grade
  belongs_to :teacher
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :grade
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :exam_category
end

app/models/exam_category.rb
class ExamCategory < ApplicationRecord
  has_many :exams
end

app/models/grade.rb
class Grade < ApplicationRecord
  has_many :courses
end

app/models/parent.rb
class Parent < ApplicationRecord

  has_many :students

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, ImageUploader

  GENDER = ['Male', 'Female']

end

app/models/student.rb
class Student < ApplicationRecord

  belongs_to :parent
  has_many :attendances

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, StudentUploader

  GENDER = ['Male', 'Female']
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, TeacherUploader

  GENDER = ['Male', 'Female']
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "School Management", :name => "description"}
    %meta{:content => "School Management", :name => "Nhean"}

    %title School Management

    %script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyCkSX4YNQLqzBJPKdQKuESstJxUGFK7Jg8"}


    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body{ id: "#{controller_name}_#{params[:action]}" }
    .wrapper
      = render 'partials/sidebar'
      .main-panel
        = render 'partials/topnav'
        .content
          .container-fluid
            .row
              = yield

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "School Management", :name => "description"}
    %meta{:content => "School Management", :name => "Nhean"}

    %title School Management

    %script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyCkSX4YNQLqzBJPKdQKuESstJxUGFK7Jg8"}


    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body{ id: "#{controller_name}_#{params[:action]}" }
    %br
    .col-xs-12.col-md-4.col-md-offset-4
      .card
        = yield

app/views/partials/_sidebar.html.haml
.sidebar{"data-color" => "blue", "data-image" => "/img/sidebar-4.jpg"}
  /
    Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
    Tip 2: you can also add an image using data-image tag
  .sidebar-wrapper
    .logo
      %a.simple-text{:href => "http://www.facebook.com/vandy.sodanhean"}
        School Management
    %ul.nav
      %li.active
        %a{:href => "dashboard.html"}
          %i.pe-7s-graph
          %p Dashboard
      %li
        = link_to current_user do
          %i.pe-7s-user
          %p User Profile
      %li
        = link_to students_url do
          %i.pe-7s-study
          %p Students
      %li
        = link_to teachers_url do
          %i.pe-7s-id
          %p Teachers
      %li
        = link_to parents_url do
          %i.pe-7s-users
          %p Parents
      %li
        = link_to courses_url do
          %i.pe-7s-ribbon
          %p Courses
      %li
        = link_to classrooms_url do
          %i.pe-7s-culture
          %p Class Rooms
      %li
        = link_to grades_url do
          %i.pe-7s-note2
          %p Grade
      %li
        = link_to exam_categories_url do
          %i.pe-7s-note2
          %p Exam Categories
      %li
        = link_to exams_url do
          %i.pe-7s-note2
          %p Exams
      %li
        = link_to attendances_url do
          %i.pe-7s-note2
          %p Attendance

app/views/partials/_topnav.html.haml
%nav.navbar.navbar-default.navbar-fixed
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => "#navigation-example-2", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"}
        = controller_name.capitalize
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-left
        %li
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.fa.fa-dashboard
            Dashboard
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.fa.fa-globe
            Notifications
            %b.caret
          %ul.dropdown-menu
            %li
              %a{:href => "#"} Notification 1
        %li
          %a{:href => ""}
            %i.fa.fa-search
            Search
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.fa.fa-user-circle-o
            My Account
            %b.caret
          %ul.dropdown-menu
            %li
              %a{:href => "#"}
                %i.fa.fa-edit
                Edit Profile
            %li
              %a{:href => "#"}
                %i.fa.fa-gears
                Setting
        %li
          = link_to destroy_user_session_url, method: :delete do
            %i.fa.fa-power-off
            Log out