config/routes.rb
Rails.application.routes.draw do

  scope 'auth' do
    devise_for :parents
    devise_for :teachers
    devise_for :students
    devise_for :users
  end

  resources :users
  resources :parents
  resources :teachers
  resources :exam_categories
  resources :grades

  resources :students
  resources :exams
  resources :courses
  resources :attendances
  resources :classrooms

  root 'dashboard#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :student
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :grade
  belongs_to :teacher
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :grade
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :exam_category
end

app/models/exam_category.rb
class ExamCategory < ApplicationRecord
  has_many :exams
end

app/models/grade.rb
class Grade < ApplicationRecord
  has_many :courses
end

app/models/parent.rb
class Parent < ApplicationRecord

  has_many :students

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, ImageUploader

  GENDER = ['Male', 'Female']

end

app/models/student.rb
class Student < ApplicationRecord

  belongs_to :parent
  has_many :attendances

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, StudentUploader

  GENDER = ['Male', 'Female']
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, TeacherUploader

  GENDER = ['Male', 'Female']
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update_without_password(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :email, :password, :gender, :dob, :phone, :address, :lat, :long, :image, :image_cache)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/teachers/_form.html.haml
= simple_form_for(@teacher) do |f|
  = f.error_notification
  .row
    .col-xs-12.col-md-6
      .image-uploader{align: 'center'}
        %a{:href => "#!"}
          = image_tag f.object.image, size: '150x150'
        = f.input :image, as: :file, label: 'Upload Image',
          :label_html => { class: 'btn btn-default'}
        = f.hidden_field :image_cache

      = f.input :name
      = f.input :email
      = f.input :password
      = f.input :dob
      = f.input :phone
      = f.input :gender, collection: Teacher::GENDER
      = f.input :address

    .col-xs-12.col-md-6
      = f.input :lat, as: :hidden, input_html: {id: 'teacher-lat'}
      = f.input :long, as: :hidden, input_html: {id: 'teacher-long'}

      #map-teacher

  = f.button :submit, class: 'btn btn-primary btn-fill'

app/views/teachers/edit.html.haml
.col-xs-12.col.md-12
  .card

    .header
      %h4.title Edit Tarent
      %hr

    .content
      = render 'form'

    %hr
    .footer

      = link_to teachers_path, class: 'btn btn-default' do
        %i.fa.fa-chevron-left  
        Back
      = link_to @teacher, class: 'btn btn-info btn-fill' do
        %i.fa.fa-eye
        Show
    %br

app/views/teachers/index.html.haml
.col-xs-12.col.md-12
  .card

    .header
      %h4.title
        %i.pe-7s-users
        Listing Teachers
      %hr
      = link_to new_teacher_path, class: 'btn btn-primary btn-fill' do
        %i.fa.fa-plus-square
        New Teacher
      %br
      %br

    .content.table-responsive.table-full-width
      %table.table.table-hover.table-striped
        %thead
          %tr
            %th Name
            %th Gender
            %th Phone
            %th Address
            %th Actions

        %tbody
          - @teachers.each do |teacher|
            %tr
              %td= teacher.name
              %td= teacher.gender
              %td= teacher.phone
              %td= teacher.address
              %td
                = link_to teacher, class: 'btn btn-info btn-sm' do
                  %i.fa.fa-eye
                  Show
                = link_to edit_teacher_path(teacher), class: 'btn btn-primary btn-sm' do
                  %i.fa.fa-edit
                  Edit
                = link_to teacher, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do
                  %i.fa.fa-trash
                  Delete
    %br

app/views/teachers/new.html.haml
.col-xs-12.col.md-12
  .card

    .header
      %h4.title New Teacher
      %hr

    .content
      = render 'form'

    %hr
    .footer
      = link_to teachers_path, class: 'btn btn-default' do
        %i.fa.fa-chevron-left
        Back
    %br

app/views/teachers/show.html.haml
- if notice.present?
  .alert.alert-success{role: "alert"}= notice
.col-xs-12.col.md-12
  .card

    .header
      %h4.title Teacher
      %hr

    .content
      .row
        .col-md-6.col-xs-12
          %table.table
            %tr
              %th Image
              %td= image_tag @teacher.image, size: '150x150'
            %tr
              %th Name
              %td= @teacher.name
            %tr
              %th Gender
              %td= @teacher.gender
            %tr
              %th Date of Birth
              %td= @teacher.dob
            %tr
              %th Phone
              %td= @teacher.phone
            %tr
              %th Email
              %td= @teacher.email
            %tr
              %th Address
              %td= @teacher.address
        .col-md-6.col-xs-12
          %input#lat-value{value: @teacher.lat, type: 'hidden'}
          %input#long-value{value: @teacher.long, type: 'hidden'}
          #show-teacher-map

    .footer
      = link_to teachers_path, class: 'btn btn-default' do
        %i.fa.fa-chevron-left
        Back
      = link_to edit_teacher_path(@teacher), class: 'btn btn-primary btn-fill' do
        %i.fa.fa-edit
        Edit
    %br