config/routes.rb
Rails.application.routes.draw do

  scope 'auth' do
    devise_for :parents
    devise_for :teachers
    devise_for :students
    devise_for :users
  end

  resources :users
  resources :parents
  resources :teachers
  resources :exam_categories
  resources :grades

  resources :students
  resources :exams
  resources :courses
  resources :attendances
  resources :classrooms

  root 'dashboard#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :student
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :grade
  belongs_to :teacher
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :grade
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :exam_category
end

app/models/exam_category.rb
class ExamCategory < ApplicationRecord
  has_many :exams
end

app/models/grade.rb
class Grade < ApplicationRecord
  has_many :courses
end

app/models/parent.rb
class Parent < ApplicationRecord

  has_many :students

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, ImageUploader

  GENDER = ['Male', 'Female']

end

app/models/student.rb
class Student < ApplicationRecord

  belongs_to :parent
  has_many :attendances

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, StudentUploader

  GENDER = ['Male', 'Female']
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, TeacherUploader

  GENDER = ['Male', 'Female']
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:exam_category_id, :name, :start_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/exams/_form.html.haml
= simple_form_for(@exam) do |f|
  = f.error_notification
  .row
    .col-xs-12.col-md-6

      = f.input :name
      = f.input :start_date
      = f.input :exam_category_id, collection: ExamCategory.all

  = f.button :submit, class: 'btn btn-primary btn-fill'

app/views/exams/edit.html.haml
.col-xs-12.col.md-12
  .card

    .header
      %h4.title Edit Exam
      %hr

    .content
      = render 'form'

    %hr
    .footer

      = link_to exams_path, class: 'btn btn-default' do
        %i.fa.fa-chevron-left  
        Back
      = link_to @exam, class: 'btn btn-info btn-fill' do
        %i.fa.fa-eye
        Show
    %br

app/views/exams/index.html.haml
.col-xs-12.col.md-12
  .card

    .header
      %h4.title
        %i.pe-7s-note2
        Listing Exam
      %hr
      = link_to new_exam_path, class: 'btn btn-primary btn-fill' do
        %i.fa.fa-plus-square
        New Exam
      %br
      %br

    .content.table-responsive.table-full-width
      %table.table.table-hover.table-striped
        %thead
          %tr
            %th Name
            %th Start date
            %th Exam category
            %th Actions

        %tbody
          - @exams.each do |exam|
            %tr
              %td= exam.name
              %td= exam.start_date
              %td= exam.exam_category.name
              %td
                = link_to exam, class: 'btn btn-info btn-sm' do
                  %i.fa.fa-eye
                  Show
                = link_to edit_exam_path(exam), class: 'btn btn-primary btn-sm' do
                  %i.fa.fa-edit
                  Edit
                = link_to exam, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do
                  %i.fa.fa-trash
                  Delete
    %br

app/views/exams/new.html.haml
.col-xs-12.col.md-12
  .card

    .header
      %h4.title New Exam
      %hr

    .content
      = render 'form'

    %hr
    .footer
      = link_to exams_path, class: 'btn btn-default' do
        %i.fa.fa-chevron-left
        Back
    %br

app/views/exams/show.html.haml
- if notice.present?
  .alert.alert-info{role: "alert"}= notice
.col-xs-12.col.md-12
  .card

    .header
      %h4.title Exam
      %hr

    .content
      .row
        .col-md-6.col-xs-12
          %table.table
            %tr
              %th Name
              %td= @exam.name
            %tr
              %th Date
              %td= @exam.start_date
            %tr
              %th Exam Category
              %td= @exam.exam_category.name
            

    .footer
      = link_to exams_path, class: 'btn btn-default' do
        %i.fa.fa-chevron-left
        Back
      = link_to edit_exam_path(@exam), class: 'btn btn-primary btn-fill' do
        %i.fa.fa-edit
        Edit
    %br